### ISSUE TITLE
exception when reading midi file

### ISSUE THREAD

**Issue by YuenSzeHong** [baskeboler/clj-karaoke-lyrics#3]
stacktrace for the exception when reading the given sample
```
java -jar ./clj-karaoke-lyrics-1.0.8-standalone.jar 'song.mid' 'song.ass' --type ass
Can not open line
Failed to load song data from  song.mid
Exception in thread "main" java.lang.IllegalArgumentException: Key must be integer
        at clojure.lang.APersistentVector.assoc(APersistentVector.java:347)
        at clojure.lang.APersistentVector.assoc(APersistentVector.java:18)
        at clojure.lang.RT.assoc(RT.java:827)
        at clojure.core$assoc__5433.invokeStatic(core.clj:193)
        at clojure.core$update.invokeStatic(core.clj:6185)
        at clojure.core$update.invoke(core.clj:6177)
        at clj_karaoke.core$extract_song_data_from_file.invokeStatic(core.clj:100)
        at clj_karaoke.core$extract_song_data_from_file.invoke(core.clj:97)
        at clj_karaoke.core$_main.invokeStatic(core.clj:87)
        at clj_karaoke.core$_main.doInvoke(core.clj:71)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clj_karaoke.core.main(Unknown Source)
```

**Comment by baskeboler** [comment]
thanks, i'll check it out

**Comment by baskeboler** [comment]
improved error handling in latest commit
